
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action QuitAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar3;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Entry name_entry;

	private global::Gtk.Entry url_entry;

	private global::Gtk.Button add_button;

	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.NodeView nodeview1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.QuitAction = new global::Gtk.Action("QuitAction", global::Mono.Unix.Catalog.GetString("Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Quit");
		w1.Add(this.QuitAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menubar3\'><menu name=\'QuitAction\' action=\'QuitAction\'/></menub" +
				"ar></ui>");
		this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar3")));
		this.menubar3.Name = "menubar3";
		this.vbox1.Add(this.menubar3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.name_entry = new global::Gtk.Entry();
		this.name_entry.CanFocus = true;
		this.name_entry.Name = "name_entry";
		this.name_entry.IsEditable = true;
		this.name_entry.InvisibleChar = '●';
		this.hbox1.Add(this.name_entry);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.name_entry]));
		w3.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.url_entry = new global::Gtk.Entry();
		this.url_entry.CanFocus = true;
		this.url_entry.Name = "url_entry";
		this.url_entry.IsEditable = true;
		this.url_entry.InvisibleChar = '●';
		this.hbox1.Add(this.url_entry);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.url_entry]));
		w4.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.add_button = new global::Gtk.Button();
		this.add_button.CanFocus = true;
		this.add_button.Name = "add_button";
		this.add_button.UseUnderline = true;
		this.add_button.Label = global::Mono.Unix.Catalog.GetString("Add");
		this.hbox1.Add(this.add_button);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.add_button]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView();
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.nodeview1.Reorderable = true;
		this.scrolledwindow1.Add(this.nodeview1);
		this.vbox1.Add(this.scrolledwindow1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.scrolledwindow1]));
		w8.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 427;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
