build:
	g++ -pedantic -std=c++11 main.cpp -o srstrgen
compile:
	g++ -pedantic -std=c++11 -c st.cpp
	g++ -pedantic -std=c++11 -c b_inc.cpp
	g++ -pedantic -std=c++11 -c main.cpp

clean:
	rm -I *.o *.gch srstrgen
